GrapeSwaggerRails.options.url           = 'api/v1/swagger_doc'
GrapeSwaggerRails.options.app_name      = 'bbetter'
GrapeSwaggerRails.options.app_url       = '/'
GrapeSwaggerRails.options.api_key_name  = 'Auth-Token'
GrapeSwaggerRails.options.api_key_type  = 'header'