default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['database_username'] %>
  password: <%= ENV['database_password'] %>
  pool: 5
development:
  <<: *default
  database: bbetter_development
test:
  <<: *default
  database: bbetter_test
production:
  <<: *default
  database: bbetter_production
